export enum Tokens {
  Moon = "MOON",
  USDCE = "USDC.e",
  USDC = "USDC",
  WETH = "WETH",
  WBTC = "WBTC",
  USDT = "USDT",
  SNX = "SNX",
  WSTETH = "wstETH",
  DAI = "DAI",
  SDAI = "sDAI",
  PYUSD = "PYUSD",
  GUARD = "GUARD",
  ETH = "ETH",
  MTK = "MTK",
  FUD = "FUD",
  FOMO = "FOMO",
  ALPHA = "ALPHA",
  KEK = "KEK",
  GLTR = "GLTR",
  STIME = "STIME",
  WEETH = "weETH", // ether.fi
  RSWETH = "rswETH", // Swell
  RSETH = "rsETH", // Kelp
  SUSDE = "sUSDe", // ethena usd
  USDE = "USDe", // ethena usd
  LBTC = "LBTC", //Lombard Bitcoin
  CBBTC = "cbBTC", // Coinbase wrapped bitcoin
  EBTC = "eBTC", // ether.fi bitcoin
  OP = "OP", // Optimism
  SOLVBTC = "SolvBTC", // Solv wrapped bitcoin
  SOLVBTCBBN = "SolvBTCBBN", // Solv wrapped babylon bitcoin
  DEUSD = "deUSD", // Solv wrapped babylon bitcoin
  WEETHC = "weETHC", // Lyra tokenized subaccount shares
  RSWETHC = "rswETHC", // Lyra tokenized subaccount shares
  RSETHC = "rsETHC", // Lyra tokenized subaccount shares
  SUSDEBULL = "sUSDeBULL", // Lyra tokenized subaccount shares
  WEETHBULL = "weETHBULL", // Lyra tokenized subaccount shares
  WEETHCS = "weETHCS", // Lyra tokenized subaccount shares
  LBTCCS = "LBTCCS", // Lyra tokenized subaccount shares
  LBTCPS = "LBTCPS", // Lyra tokenized subaccount shares
  LBTCB = "LBTCB", // Lyra tokenized subaccount shares
  WEETHB = "weETHB", // Lyra tokenized subaccount shares
  OLAS = "OLAS",
  AAVE = "AAVE",
  MUSD = "MUSD", // Mezo USD
  HYPE = "HYPE",
  PUFETH = "PUFETH",
  KHYPE = "KHYPE",
  USDH = "USDH",
  jitoSOL = "jitoSOL",
  cbADA = "cbADA",
  BTC = "BTC",
  XAUT = "XAUT",
  FXRP = "FXRP",
  HEMIBTC = "HEMIBTC",
}
