import { Tokens } from "./tokens";

export const tokenDecimals: { [key in Tokens]: number } = {
  [Tokens.Moon]: 18,
  [Tokens.USDC]: 6,
  [Tokens.USDCE]: 6,
  [Tokens.WETH]: 18,
  [Tokens.WBTC]: 8,
  [Tokens.USDT]: 6,
  [Tokens.SNX]: 18,
  [Tokens.WSTETH]: 18,
  [Tokens.DAI]: 18,
  [Tokens.SDAI]: 18,
  [Tokens.GUARD]: 18,
  [Tokens.ETH]: 18,
  [Tokens.MTK]: 18,
  [Tokens.FUD]: 18,
  [Tokens.FOMO]: 18,
  [Tokens.ALPHA]: 18,
  [Tokens.KEK]: 18,
  [Tokens.GLTR]: 18,
  [Tokens.STIME]: 18,

  [Tokens.WEETH]: 18,
  [Tokens.RSWETH]: 18,
  [Tokens.RSETH]: 18,
  [Tokens.SUSDE]: 18,
  [Tokens.USDE]: 18,
  [Tokens.LBTC]: 8,
  [Tokens.CBBTC]: 8,
  [Tokens.EBTC]: 8,
  [Tokens.OP]: 18,
  [Tokens.SOLVBTC]: 18,
  [Tokens.SOLVBTCBBN]: 18,
  [Tokens.DEUSD]: 18,
  [Tokens.OLAS]: 18,
  [Tokens.AAVE]: 18,
  [Tokens.MUSD]: 18,
  [Tokens.HYPE]: 18,
  [Tokens.PUFETH]: 18,
  [Tokens.KHYPE]: 18,
  [Tokens.USDH]: 6,
  [Tokens.cbADA]: 6,
  [Tokens.BTC]: 8,
};
